name: CI
codex/generate-monorepo-for-financely-ui-and-backend
on: [push]

on:
  push:
    branches: [ main ]
 main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
codex/generate-monorepo-for-financely-ui-and-backend
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
        working-directory: ./financely/apps/web
      - name: Run lint
        run: npm run lint
        working-directory: ./financely/apps/web
      - name: Run tests
        run: npm test -- --runInBand
        working-directory: ./financely/apps/web

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run lint
      - run: npm test
 main
